export const UI_DOCS = {
  en: {
    skip: "Skip to content",
    skipHome: "Skip to gallery",
    navAria: "Primary",
    navProjects: "Projects",
    navBte: "BuildTheEarth",
    navDev: "Development",
    navGallery: "Gallery",
    navAbout: "About",
    navContact: "Contact",
    breadcrumbAria: "Breadcrumb",
    crumbHome: "Home",
    footerAria: "Footer",
    footerPortfolio: "Portfolio",
    footerShots: "All screenshots",
    footerSearch: "Search",
    footerAbout: "About MaxLananas",
    footerProfileFr: "Profile in French",
    footerProfileEs: "Profile in Spanish",
    footerCopy: "Independent personal portfolio. All creations remain the property of their respective owners.",
    searchPlaceholder: "Search builds...",
    searchAria: "Search builds",
    clearAria: "Clear search",
    tabsAria: "Filter builds",
    tabAll: "All",
    tabOriginals: "Originals",
    tabCollabs: "Collaborations",
    shuffleAria: "Shuffle order",
    displayAria: "Display settings",
    langAria: "Language",
    onThisPage: "On this page",
    tocAria: "On this page",
    sectionDoes: "What the project does",
    sectionExplore: "Explore the collection",
    sectionEnv: "Environment and requirements",
    sectionStart: "Getting started",
    sectionUsing: "Using these references",
    sectionShots: "Screenshots and credits",
    sectionFaq: "Questions about this tool",
    sectionExampleBuilds: "Example builds from this portfolio",
    sectionScope: "Scope, limitations and attribution",
    sectionSources: "Project sources",
    sectionRelated: "Related work",
    relatedAll: "All projects",
    relatedBte: "BuildTheEarth work and tools",
    relatedDev: "Development projects",
    reviewedOn: "reviewed on {date}",
    modrinthPrimary: "Modrinth is the primary destination for current releases and compatibility.",
    followSource: "Follow the linked source for the project’s current scope.",
    versionsDownloads: "Versions and downloads",
    publicRepo: "Public GitHub repository",
    byline: "By {author} · {date}",
    updated: "Updated {date}",
    prevPage: "Previous page",
    nextPage: "Next page",
    pageNavAria: "Gallery pages",
    coverAlt: "{name} interface screenshot published on Modrinth",
    coverCaption: "Published project screenshot; check the release page for the current interface.",
    modrinthCaption: "Image from the project’s Modrinth gallery; the interface may differ between releases.",
    cardAlt: "{name} — visual preview",
    creditLogoAlt: "{name} logo",
    enlarge: "Enlarge {title}",
    videoStart: "Play the walkthrough video",
    offlineNote: "Offline. Please reconnect to load this page.",
    reqModrinth: "Download the release matching your Minecraft version and loader, then follow its listed dependencies and the rules of the server you use.",
    launchModrinth: "View on Modrinth",
    launchGithub: "Explore on GitHub",
    launchSource: "Original presentation ↗",
    launchApp: "Open the live tool ↗",
    launchContact: "Discuss a project",
    sourceModrinth: "Project description and releases on Modrinth",
    sourceRepo: "Reviewed repository documentation",
    sourceLive: "The live tool and its own documentation",
    sourceDrive: "Creator-supplied presentation on Google Drive",
    projectSources: "Project sources",
    projectImage: "Project image",
    screenshotsTitle: "Explore the eleven visuals",
    screenshotsBody: "Select an image to enlarge it. Keyboard arrows move through the presentation; the displayed data is fictitious.",
    videoTitle: "Watch the redesign",
    videoBody: "Independent presentation with fictitious data. The native player needs no iframe or Google connection to play the video.",
    videoAria: "iProf 2026 redesign walkthrough",
    videoAriaShort: "iProf video walkthrough",
    videoUnsupported: "Your browser does not support this video.",
    videoPlay: "Play the video",
    videoOpen: "Open the video file",
    videoDuration: "47.68 seconds",
    videoOnDemand: "Loaded on request",
    videoDescSummary: "Text description of the on-screen sequence",
    videoDescBody: "The film opens with public-service visual references and the iProf title. It then shows the dashboard and its deadlines, the career view and its progression, followed by the public-facing page. It ends with the presentation summary. Figures and claims visible in the film belong to the supplied mockup, not measured usage results established by this case study. This describes the images, not a transcription of the audio track.",
    genreDesign: "Independent interface redesign",
    scopeNotice: "Independent interface redesign · fictitious demonstration data · not an official login service",
    pageOf: "Page {page} of {total}",
    provenanceUpstream: "This page presents an adaptation of BuildersUtilities by TehBrian, itself built on Builder’s Utilities by Arcaniax.",
    cardBuilds: "Build screenshots",
    interfaceStudy: "Interface study",
    navWork: "Work",
    joinDiscord: "Join Discord",
    discordLabel: "Discord",
    quickNavAria: "Quick navigation",
    quickNavCta: "Join the community",
    gridDensity: "Grid density",
    densityCozy: "Cozy",
    densityCompact: "Compact",
    lbViewer: "Build photo viewer",
    lbClose: "Close",
    lbPrev: "Previous",
    lbNext: "Next",
    lbOriginalTitle: "Full-quality original file (may be large)",
    lbOpenOriginal: "Open original ↗",
    lbRetry: "Retry",
    footerCopyHome: "All builds shown remain the property of their respective owners.",
    viewCollection: "View the {name} collection",
    caseRole: "Role",
    caseStack: "Technical context",
    caseScope: "Presented material",
    caseEvidence: "What the evidence supports",
    caseStudioNote: "Studio note",
    caseSourcesReviewed: "Sources reviewed",
    caseKicker: "Interfaces & tools",
    caseDarkAlt: "Dark-theme mockup and accessibility intentions",
    casePhoneAlt: "Presentation of the mockup on a phone",
    caseMediaAlt: "iProf 2026 redesign — {title}",
    caseBy: "By",
    caseUpdated: "Updated",
    sectionDesignFocus: "Design focus",
    sectionDesignScope: "Scope and attribution",
    upstreamNote: "Upstream: {upstream}, derived from {original}. {license} before reuse.",
    upstreamLicense: "Read the repository license",
    artworkRole: "Project icon (credited on Modrinth)",
    pageShort: "Page {page}",
    prevLink: "← Previous",
    nextLink: "Next →",
    creditProjectMedia: "Project presentation supplied by MaxLananas",
    creditDefault: "From MaxLananas’s personal build portfolio",
    schemaPersonDescription: "Minecraft builder and developer of client mods, server plugins, building tools and software interfaces.",
    schemaContactType: "Project inquiries",
    schemaKnowsAbout: "Minecraft building,BuildTheEarth,Java development,Web development,Software interfaces,Interface design",
    schemaGenreUnofficial: "Unofficial community documentation",
    schemaCreditUpstream: "BT Corsica adaptation by MaxLananas; upstream BuildersUtilities by TehBrian and Arcaniax.",
    schemaCreditBte: "Made within BuildTheEarth France; portfolio contribution by MaxLananas.",
    schemaVideoName: "iProf 2026 redesign walkthrough",
    schemaVideoDescription: "Creator-supplied walkthrough of the iProf 2026 interface redesign.",
    ogDefaultAlt: "MaxLananas — Minecraft builds and developer projects",
    ogProjectAlt: "{name} — project presentation by MaxLananas",
    brandAria: "MaxLananas home",
    coverTitle: "{name} — project image",
    coverTitleInterface: "{name} — interface",
    coverAltGallery: "{name} interface screenshot from its Modrinth gallery"
  },
  fr: {
    skip: "Aller au contenu",
    skipHome: "Aller à la galerie",
    navAria: "Navigation principale",
    navProjects: "Projets",
    navBte: "BuildTheEarth",
    navDev: "Développement",
    navGallery: "Galerie",
    navAbout: "Profil",
    navContact: "Contact",
    breadcrumbAria: "Fil d’Ariane",
    crumbHome: "Accueil",
    footerAria: "Pied de page",
    footerPortfolio: "Portfolio",
    footerShots: "Toutes les captures",
    footerSearch: "Recherche",
    footerAbout: "À propos de MaxLananas",
    footerProfileFr: "Profil en français",
    footerProfileEs: "Profil en espagnol",
    footerCopy: "Portfolio personnel indépendant. Les créations restent la propriété de leurs auteurs respectifs.",
    searchPlaceholder: "Rechercher un build...",
    searchAria: "Rechercher un build",
    clearAria: "Effacer la recherche",
    tabsAria: "Filtrer les builds",
    tabAll: "Tous",
    tabOriginals: "Créations personnelles",
    tabCollabs: "Collaborations",
    shuffleAria: "Mélanger l’ordre",
    displayAria: "Réglages d’affichage",
    langAria: "Langue",
    onThisPage: "Sur cette page",
    tocAria: "Sur cette page",
    sectionDoes: "Ce que fait le projet",
    sectionExplore: "Explorer la collection",
    sectionEnv: "Environnement et prérequis",
    sectionStart: "Premiers pas",
    sectionUsing: "Utiliser ces références",
    sectionShots: "Captures et crédits",
    sectionFaq: "Questions sur cet outil",
    sectionExampleBuilds: "Builds d’exemple issus de ce portfolio",
    sectionScope: "Périmètre, limites et attribution",
    sectionSources: "Sources du projet",
    sectionRelated: "Travaux liés",
    relatedAll: "Tous les projets",
    relatedBte: "Outils et travaux BuildTheEarth",
    relatedDev: "Projets de développement",
    reviewedOn: "revu le {date}",
    modrinthPrimary: "Modrinth reste la référence pour les versions actuelles et la compatibilité.",
    followSource: "Suivez la source liée pour connaître le périmètre actuel du projet.",
    versionsDownloads: "Versions et téléchargements",
    publicRepo: "Dépôt GitHub public",
    byline: "Par {author} · {date}",
    updated: "Mis à jour le {date}",
    prevPage: "Page précédente",
    nextPage: "Page suivante",
    pageNavAria: "Pages de la galerie",
    coverAlt: "Capture d’interface de {name} publiée sur Modrinth",
    coverCaption: "Capture publiée du projet ; consultez la page de release pour l’interface actuelle.",
    modrinthCaption: "Image issue de la galerie Modrinth du projet ; l’interface peut varier selon les versions.",
    cardAlt: "{name} — aperçu visuel",
    creditLogoAlt: "Logo {name}",
    enlarge: "Agrandir {title}",
    videoStart: "Lire la vidéo de présentation",
    offlineNote: "Hors ligne. Reconnectez-vous pour charger cette page.",
    reqModrinth: "Téléchargez la release correspondant à votre version de Minecraft et à votre loader, puis suivez ses dépendances indiquées et les règles du serveur que vous utilisez.",
    launchModrinth: "Voir sur Modrinth",
    launchGithub: "Explorer sur GitHub",
    launchSource: "Présentation d’origine ↗",
    launchApp: "Ouvrir l’outil en ligne ↗",
    launchContact: "Discuter d’un projet",
    sourceModrinth: "Description du projet et releases sur Modrinth",
    sourceRepo: "Documentation du dépôt examinée",
    sourceLive: "L’outil en ligne et sa propre documentation",
    sourceDrive: "Présentation fournie par l’auteur sur Google Drive",
    projectSources: "Sources du projet",
    projectImage: "Image du projet",
    screenshotsTitle: "Explorer les onze visuels",
    screenshotsBody: "Sélectionnez une image pour l’agrandir. Les flèches du clavier permettent de parcourir la présentation ; les données affichées sont fictives.",
    videoTitle: "La refonte en vidéo",
    videoBody: "Présentation indépendante avec données fictives. Le lecteur natif ne demande ni iframe ni connexion à Google pour lire la vidéo.",
    videoAria: "Présentation vidéo de la refonte iProf 2026",
    videoAriaShort: "Présentation vidéo iProf",
    videoUnsupported: "Votre navigateur ne prend pas en charge cette vidéo.",
    videoPlay: "Lire la vidéo",
    videoOpen: "Ouvrir le fichier vidéo",
    videoDuration: "47,68 secondes",
    videoOnDemand: "Lecture à la demande",
    videoDescSummary: "Description textuelle de la séquence affichée",
    videoDescBody: "Le film ouvre sur les références visuelles au service public, puis présente le titre iProf. Il montre ensuite le tableau de bord et ses échéances, la vue carrière avec sa progression, puis la vitrine publique. Il se termine par la synthèse de la présentation. Les chiffres et promesses affichés dans le film font partie de la maquette fournie ; ils ne constituent pas des mesures d’usage réalisées pour cette étude. Cette description porte sur les images, pas sur une transcription de la piste audio.",
    genreDesign: "Refonte d’interface indépendante",
    scopeNotice: "Refonte d’interface indépendante · données de démonstration fictives · aucun service de connexion officiel",
    pageOf: "Page {page} sur {total}",
    provenanceUpstream: "Cette page présente une adaptation de BuildersUtilities par TehBrian, elle-même fondée sur Builder’s Utilities d’Arcaniax.",
    cardBuilds: "Captures de builds",
    interfaceStudy: "Étude d’interface",
    navWork: "Travaux",
    joinDiscord: "Rejoindre Discord",
    discordLabel: "Discord",
    quickNavAria: "Navigation rapide",
    quickNavCta: "Rejoindre la communauté",
    gridDensity: "Densité de la grille",
    densityCozy: "Confortable",
    densityCompact: "Compacte",
    lbViewer: "Visionneuse de photos de builds",
    lbClose: "Fermer",
    lbPrev: "Précédent",
    lbNext: "Suivant",
    lbOriginalTitle: "Fichier original pleine qualité (peut être lourd)",
    lbOpenOriginal: "Ouvrir l’original ↗",
    lbRetry: "Réessayer",
    footerCopyHome: "Tous les builds présentés restent la propriété de leurs auteurs respectifs.",
    viewCollection: "Voir la collection {name}",
    caseRole: "Rôle",
    caseStack: "Support technique",
    caseScope: "Éléments présentés",
    caseEvidence: "Ce que les sources permettent d’affirmer",
    caseStudioNote: "Note d’atelier",
    caseSourcesReviewed: "Sources revues le",
    caseKicker: "Interfaces & outils",
    caseDarkAlt: "Maquette du mode sombre et intentions d’accessibilité",
    casePhoneAlt: "Présentation de la maquette sur téléphone",
    caseMediaAlt: "Refonte iProf 2026 — {title} (maquette)",
    caseBy: "Par",
    caseUpdated: "Mis à jour le",
    sectionDesignFocus: "Axes de design",
    sectionDesignScope: "Périmètre et attribution",
    upstreamNote: "Amont : {upstream}, dérivé de {original}. {license} avant toute réutilisation.",
    upstreamLicense: "Lire la licence du dépôt",
    artworkRole: "Icône du projet (créditée sur Modrinth)",
    pageShort: "Page {page}",
    prevLink: "← Précédent",
    nextLink: "Suivant →",
    creditProjectMedia: "Présentation du projet fournie par MaxLananas",
    creditDefault: "Issue du portfolio personnel de builds de MaxLananas",
    schemaPersonDescription: "Créateur de builds Minecraft et développeur de mods client, plugins serveur, outils de construction et interfaces logicielles.",
    schemaContactType: "Demandes de projets",
    schemaKnowsAbout: "Construction Minecraft,BuildTheEarth,Développement Java,Développement web,Interfaces logicielles,Design d’interface",
    schemaGenreUnofficial: "Documentation communautaire non officielle",
    schemaCreditUpstream: "Adaptation BT Corsica par MaxLananas ; BuildersUtilities en amont par TehBrian et Arcaniax.",
    schemaCreditBte: "Réalisé dans le cadre de BuildTheEarth France ; contribution au portfolio par MaxLananas.",
    schemaVideoName: "Présentation de la refonte iProf 2026",
    schemaVideoDescription: "Présentation vidéo de la refonte d’interface iProf 2026, fournie par son auteur.",
    ogDefaultAlt: "MaxLananas — builds Minecraft et projets de développement",
    ogProjectAlt: "{name} — présentation du projet par MaxLananas",
    brandAria: "Accueil MaxLananas",
    coverTitle: "{name} — image du projet",
    coverTitleInterface: "{name} — interface",
    coverAltGallery: "Capture d’interface de {name} issue de sa galerie Modrinth"
  },
  es: {
    skip: "Saltar al contenido",
    skipHome: "Saltar a la galería",
    navAria: "Navegación principal",
    navProjects: "Proyectos",
    navBte: "BuildTheEarth",
    navDev: "Desarrollo",
    navGallery: "Galería",
    navAbout: "Perfil",
    navContact: "Contacto",
    breadcrumbAria: "Ruta de navegación",
    crumbHome: "Inicio",
    footerAria: "Pie de página",
    footerPortfolio: "Portfolio",
    footerShots: "Todas las capturas",
    footerSearch: "Búsqueda",
    footerAbout: "Sobre MaxLananas",
    footerProfileFr: "Perfil en francés",
    footerProfileEs: "Perfil en español",
    footerCopy: "Portfolio personal independiente. Todas las creaciones siguen siendo propiedad de sus respectivos autores.",
    searchPlaceholder: "Buscar builds...",
    searchAria: "Buscar builds",
    clearAria: "Borrar búsqueda",
    tabsAria: "Filtrar builds",
    tabAll: "Todos",
    tabOriginals: "Creaciones propias",
    tabCollabs: "Colaboraciones",
    shuffleAria: "Mezclar el orden",
    displayAria: "Ajustes de visualización",
    langAria: "Idioma",
    onThisPage: "En esta página",
    tocAria: "En esta página",
    sectionDoes: "Qué hace el proyecto",
    sectionExplore: "Explorar la colección",
    sectionEnv: "Entorno y requisitos",
    sectionStart: "Primeros pasos",
    sectionUsing: "Usar estas referencias",
    sectionShots: "Capturas y créditos",
    sectionFaq: "Preguntas sobre esta herramienta",
    sectionExampleBuilds: "Builds de ejemplo de este portfolio",
    sectionScope: "Alcance, límites y atribución",
    sectionSources: "Fuentes del proyecto",
    sectionRelated: "Trabajos relacionados",
    relatedAll: "Todos los proyectos",
    relatedBte: "Herramientas y trabajos de BuildTheEarth",
    relatedDev: "Proyectos de desarrollo",
    reviewedOn: "revisado el {date}",
    modrinthPrimary: "Modrinth es el destino principal para las versiones actuales y la compatibilidad.",
    followSource: "Consulta la fuente enlazada para conocer el alcance actual del proyecto.",
    versionsDownloads: "Versiones y descargas",
    publicRepo: "Repositorio público en GitHub",
    byline: "Por {author} · {date}",
    updated: "Actualizado el {date}",
    prevPage: "Página anterior",
    nextPage: "Página siguiente",
    pageNavAria: "Páginas de la galería",
    coverAlt: "Captura de interfaz de {name} publicada en Modrinth",
    coverCaption: "Captura publicada del proyecto; consulta la página de la versión para ver la interfaz actual.",
    modrinthCaption: "Imagen de la galería de Modrinth del proyecto; la interfaz puede variar entre versiones.",
    cardAlt: "{name} — vista previa",
    creditLogoAlt: "Logotipo de {name}",
    enlarge: "Ampliar {title}",
    videoStart: "Reproducir el vídeo de presentación",
    offlineNote: "Sin conexión. Vuelve a conectarte para cargar esta página.",
    reqModrinth: "Descarga la versión que coincida con tu versión de Minecraft y tu cargador, y sigue sus dependencias indicadas y las reglas del servidor que uses.",
    launchModrinth: "Ver en Modrinth",
    launchGithub: "Explorar en GitHub",
    launchSource: "Presentación original ↗",
    launchApp: "Abrir la herramienta en línea ↗",
    launchContact: "Hablar de un proyecto",
    sourceModrinth: "Descripción del proyecto y versiones en Modrinth",
    sourceRepo: "Documentación del repositorio revisada",
    sourceLive: "La herramienta en línea y su propia documentación",
    sourceDrive: "Presentación aportada por el autor en Google Drive",
    projectSources: "Fuentes del proyecto",
    projectImage: "Imagen del proyecto",
    screenshotsTitle: "Explorar los once visuales",
    screenshotsBody: "Selecciona una imagen para ampliarla. Las flechas del teclado recorren la presentación; los datos mostrados son ficticios.",
    videoTitle: "El rediseño en vídeo",
    videoBody: "Presentación independiente con datos ficticios. El reproductor nativo no necesita iframe ni conexión a Google para reproducir el vídeo.",
    videoAria: "Vídeo de presentación del rediseño de iProf 2026",
    videoAriaShort: "Vídeo de presentación de iProf",
    videoUnsupported: "Tu navegador no admite este vídeo.",
    videoPlay: "Reproducir el vídeo",
    videoOpen: "Abrir el archivo de vídeo",
    videoDuration: "47,68 segundos",
    videoOnDemand: "Reproducción a demanda",
    videoDescSummary: "Descripción textual de la secuencia mostrada",
    videoDescBody: "La película abre con referencias visuales al servicio público y el título iProf. Después muestra el panel y sus plazos, la vista de carrera con su progreso y, a continuación, el escaparate público. Termina con la síntesis de la presentación. Las cifras y promesas visibles en la película forman parte de la maqueta suministrada; no son medidas de uso realizadas para este estudio. Esta descripción se refiere a las imágenes, no a una transcripción de la pista de audio.",
    genreDesign: "Rediseño de interfaz independiente",
    scopeNotice: "Rediseño de interfaz independiente · datos de demostración ficticios · no es un servicio oficial de inicio de sesión",
    pageOf: "Página {page} de {total}",
    provenanceUpstream: "Esta página presenta una adaptación de BuildersUtilities de TehBrian, basada a su vez en Builder’s Utilities de Arcaniax.",
    cardBuilds: "Capturas de builds",
    interfaceStudy: "Estudio de interfaz",
    navWork: "Trabajos",
    joinDiscord: "Únete a Discord",
    discordLabel: "Discord",
    quickNavAria: "Navegación rápida",
    quickNavCta: "Únete a la comunidad",
    gridDensity: "Densidad de la cuadrícula",
    densityCozy: "Cómodo",
    densityCompact: "Compacto",
    lbViewer: "Visor de fotos de builds",
    lbClose: "Cerrar",
    lbPrev: "Anterior",
    lbNext: "Siguiente",
    lbOriginalTitle: "Archivo original a calidad completa (puede ser grande)",
    lbOpenOriginal: "Abrir el original ↗",
    lbRetry: "Reintentar",
    footerCopyHome: "Todos los builds mostrados siguen siendo propiedad de sus respectivos autores.",
    viewCollection: "Ver la colección {name}",
    caseRole: "Rol",
    caseStack: "Contexto técnico",
    caseScope: "Material presentado",
    caseEvidence: "Lo que las fuentes permiten afirmar",
    caseStudioNote: "Nota de taller",
    caseSourcesReviewed: "Fuentes revisadas el",
    caseKicker: "Interfaces y herramientas",
    caseDarkAlt: "Maqueta del tema oscuro e intenciones de accesibilidad",
    casePhoneAlt: "Presentación de la maqueta en un teléfono",
    caseMediaAlt: "Rediseño de iProf 2026 — {title} (maqueta)",
    caseBy: "Por",
    caseUpdated: "Actualizado el",
    sectionDesignFocus: "Ejes de diseño",
    sectionDesignScope: "Alcance y atribución",
    upstreamNote: "Original: {upstream}, derivado de {original}. {license} antes de reutilizarlo.",
    upstreamLicense: "Leer la licencia del repositorio",
    artworkRole: "Icono del proyecto (acreditado en Modrinth)",
    pageShort: "Página {page}",
    prevLink: "← Anterior",
    nextLink: "Siguiente →",
    creditProjectMedia: "Presentación del proyecto suministrada por MaxLananas",
    creditDefault: "Del portfolio personal de builds de MaxLananas",
    schemaPersonDescription: "Creador de builds de Minecraft y desarrollador de mods cliente, plugins de servidor, herramientas de construcción e interfaces de software.",
    schemaContactType: "Solicitudes de proyectos",
    schemaKnowsAbout: "Construcción en Minecraft,BuildTheEarth,Desarrollo Java,Desarrollo web,Interfaces de software,Diseño de interfaces",
    schemaGenreUnofficial: "Documentación comunitaria no oficial",
    schemaCreditUpstream: "Adaptación BT Corsica por MaxLananas; BuildersUtilities original de TehBrian y Arcaniax.",
    schemaCreditBte: "Realizado dentro de BuildTheEarth France; contribución al portfolio de MaxLananas.",
    schemaVideoName: "Vídeo del rediseño de iProf 2026",
    schemaVideoDescription: "Vídeo de presentación del rediseño de interfaz iProf 2026, suministrado por su autor.",
    ogDefaultAlt: "MaxLananas — builds de Minecraft y proyectos de desarrollo",
    ogProjectAlt: "{name} — presentación del proyecto por MaxLananas",
    brandAria: "Inicio de MaxLananas",
    coverTitle: "{name} — imagen del proyecto",
    coverTitleInterface: "{name} — interfaz",
    coverAltGallery: "Captura de interfaz de {name} de su galería de Modrinth"
  }
};
