import { SITE, PAGE_SIZE, galleryPath, projectPath } from "../content/site.js";
import { PROJECTS, FEATURED_PROJECT_SLUGS, developmentProjects } from "../content/projects.js";
import { projectCard, iprofSpotlight, projectScreenshots, projectVideo, mediaData, projectPicture } from "./project-content.mjs";
import { FILES, CREDITS } from "../gallery-data.js";
import { imageLabel } from "../image-labels.js";
import { proxyUrl, originalUrl } from "../image-utils.js";

export const escape = (value = "") => String(value).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
export function helpers(base = "/", manifest = {}) {
  const local = (path) => base + path.replace(/^\//, "");
  const link = (path, label, attributes = "") => `<a href="${escape(/^https?:/.test(path) ? path : local(path))}"${attributes ? " " + attributes : ""}>${escape(label)}</a>`;
  const cards = (projects) => `<div class="project-grid">${projects.map((p) => projectCard(p, { local, link })).join("")}</div>`;
  const imageData = (item) => {
    const meta = manifest[item.name];
    if (!meta) return { src: proxyUrl(item, 640), width: 640, height: 480 };
    const widths = meta.widths.filter((w) => w <= 960);
    if (!widths.length) widths.push(meta.widths[0]);
    const width = widths.find((w) => w >= 640) || widths[widths.length - 1];
    return { src: local(`${meta.base}-${width}.webp`), width: meta.width, height: meta.height,
      avif: widths.map((w) => `${local(`${meta.base}-${w}.avif`)} ${w}w`).join(", "),
      webp: widths.map((w) => `${local(`${meta.base}-${w}.webp`)} ${w}w`).join(", ") };
  };
  const photos = (items, eager = true) => `<div class="photo-grid">${items.map((item, position) => {
    const index = FILES.findIndex((file) => file.name === item.name);
    const image = imageData(item);
    const credit = CREDITS[item.credit];
    const label = imageLabel(item, index);
    const project = PROJECTS.find((p) => p.images?.includes(item.name));
    return `<figure class="photo-card" id="image-${index + 1}"><a class="photo-media" href="${escape(originalUrl(item))}" target="_blank" rel="noopener" aria-label="${escape(`Open original: ${label}`)}"><picture>${image.avif ? `<source type="image/avif" srcset="${escape(image.avif)}" sizes="(max-width: 640px) 92vw, (max-width: 1000px) 44vw, 30vw">` : ""}<img src="${escape(image.src)}" ${image.webp ? `srcset="${escape(image.webp)}" sizes="(max-width: 640px) 92vw, (max-width: 1000px) 44vw, 30vw" ` : ""}width="${image.width}" height="${image.height}" alt="${escape(`${label} — MaxLananas (#${String(index + 1).padStart(3, "0")})`)}" loading="${position === 0 && eager ? "eager" : "lazy"}" fetchpriority="${position === 0 && eager ? "high" : "low"}" decoding="async" data-original="${escape(originalUrl(item))}"></picture></a><figcaption><strong>${escape(label)}</strong><p>${credit ? escape(credit.text) + " " + (credit.linkUrl ? link(credit.linkUrl, credit.linkText) : escape(credit.linkText)) : "From MaxLananas’s personal build portfolio."}</p>${project ? `<p>${link(projectPath(project.slug), "View the " + project.name + " collection")}</p>` : ""}<small>Image ${index + 1} · ${escape(item.name)}</small></figcaption></figure>`;
  }).join("")}</div>`;
  return { local, link, cards, photos, imageData, mediaData: (key) => mediaData(key, local) };
}

export function homeIntro(page, h) {
  if (page.noindex) return `<h1>${escape(page.heading)}</h1><p>Search screenshots by subject, filename or collaboration. For software, see ${h.link("/projects/", "the project catalogue")}; without JavaScript, use ${h.link("/builds/", "the paginated build gallery")}.</p>`;
  return `<h1>MaxLananas</h1><p class="identity-line">Minecraft builder &amp; developer</p><p>I design interfaces, create Minecraft builds and develop software tools. See my ${h.link("/projects/iprof-redesign/", "iProf redesign")}, ${h.link("/buildtheearth/", "BuildTheEarth-related work")}, ${h.link("/development/", "development projects")} and ${h.link("/about/", "creator profile")}.</p>`;
}
export function homeProjects(h) {
  const selected = FEATURED_PROJECT_SLUGS.filter((slug) => slug !== "iprof-redesign").map((slug) => PROJECTS.find((p) => p.slug === slug));
  const iprof = PROJECTS.find((p) => p.slug === "iprof-redesign");
  return `<section class="site-section" aria-labelledby="projectsHeading"><p class="eyebrow">Interfaces, tools & experiments</p><h2 id="projectsHeading">Beyond the blocks</h2><p>From the iProf redesign to published Minecraft releases and systems experiments: a closer look at the development side of my work.</p>${iprofSpotlight(iprof, h)}${h.cards(selected)}<p class="section-links">${h.link("/development/", "Explore development projects")} · ${h.link(SITE.modrinth, "Find my releases on Modrinth")}</p></section>`;
}

export function pageContent(page, h) {
  const { link, cards, photos } = h;
  if (page.project) {
    const p = page.project;
    const sourceUrl = p.source?.url || (p.repo && p.revision ? p.repo + "/blob/" + p.revision + "/" + p.evidenceFile : p.repo);
    const primary = p.modrinth ? link(p.modrinth, "View on Modrinth", 'class="btn-pill-solid"')
      : p.repo ? link(p.repo, "Explore on GitHub", 'class="btn-pill-solid"')
      : p.source ? link(p.source.url, "Original presentation ↗", 'class="text-link"') : link("/#contact", "Discuss a project", 'class="btn-pill-solid"');
    const provenance = sourceUrl ? `<section class="source-note"><h2>Project sources</h2><p>${link(sourceUrl, p.source?.label || "Reviewed repository documentation")} · reviewed on <time datetime="${SITE.reviewed}">7 September 2026</time>. ${p.modrinth ? "Modrinth is the primary destination for current releases and compatibility." : "Follow the linked source for the project’s current scope."}</p>${p.modrinth ? `<p>${link(p.modrinth + "/versions", "Versions and downloads")}${p.repo ? " · " + link(p.repo, "Public GitHub repository") : ""}</p>` : ""}${p.artwork ? `<p>${escape(p.artwork.role)}: ${link(p.artwork.url, p.artwork.name)}.</p>` : ""}</section>` : "";
    const related = `<section><h2>Related work</h2>${cards(p.related.map((slug) => PROJECTS.find((project) => project.slug === slug)))}<p class="section-links">${link("/projects/", "All projects")} · ${link(p.bte ? "/buildtheearth/" : "/development/", p.bte ? "BuildTheEarth work and tools" : "Development projects")}</p></section>`;
    const intro = `<p class="eyebrow">${escape(p.category)}</p>${p.intro.map((text) => `<p>${escape(text)}</p>`).join("")}<div class="project-actions">${primary}</div>`;
    if (p.kind === "design") return `<figure class="project-single-image project-lead-image">${projectPicture(p.leadMedia || p.cover, h, { alt: `${p.name} — interface preview`, eager: true, sizes: "(max-width: 1100px) 92vw, 1050px" })}</figure>${intro}<p class="project-scope-notice">Independent interface redesign · fictitious demonstration data · not an official login service</p>${projectVideo(p, h)}${projectScreenshots(p, h)}<section><h2>Design focus</h2><ul>${p.features.map((text) => `<li>${escape(text)}</li>`).join("")}</ul></section><section><h2>Scope and attribution</h2><p>${escape(p.limits)}</p></section>${provenance}${related}`;
    return `${intro}${projectScreenshots(p, h)}
      <section><h2>${p.kind === "build" ? "Explore the collection" : "What the project does"}</h2><ul>${p.features.map((text) => `<li>${escape(text)}</li>`).join("")}</ul></section>
      ${p.requirements ? `<section><h2>Environment and requirements</h2><p>${escape(p.requirements)}</p></section>` : ""}
      <section><h2>${p.kind === "build" ? "Using these references" : "Getting started"}</h2><p>${escape(p.usage)}</p></section>
      ${p.images ? `<section><h2>Screenshots and credits</h2>${photos(p.images.map((name) => FILES.find((file) => file.name === name)))}</section>` : ""}
      <section><h2>Scope, limitations and attribution</h2><p>${escape(p.limits)}</p>${p.upstream ? `<p>Upstream: ${link(p.upstream, "TehBrian’s BuildersUtilities")}, derived from ${link("https://www.spigotmc.org/resources/builders-utilities.42361/", "Arcaniax’s Builder’s Utilities")}. ${link(p.repo + "/blob/" + p.revision + "/LICENSE", "Read the repository license")} before reuse.</p>` : ""}</section>
      ${provenance}${related}`;
  }

  if (page.type === "ProfilePage") {
    const french = page.lang === "fr";
    const languages = `<nav class="language-nav" aria-label="${french ? "Langue" : "Language"}">${link("/about/", "English", 'lang="en" hreflang="en"')} · ${link("/fr/a-propos/", "Français", 'lang="fr" hreflang="fr"')}</nav>`;
    if (french) return `${languages}<p class="eyebrow">Créations Minecraft · Développement</p><p>Je suis MaxLananas, créateur de constructions Minecraft et développeur. Ce portfolio relie mes captures de builds, mes contributions autour de BuildTheEarth et les outils que je développe pour construire, naviguer ou créer des interfaces.</p><p>Le même nom, <strong>MaxLananas</strong>, identifie ce portfolio et mon profil GitHub. Les liens ci-dessous permettent de retrouver mes dépôts, mes publications et le point de contact du portfolio.</p>
      <section><h2>Construction et BuildTheEarth</h2><p>La ${link("/builds/", "galerie de constructions")} conserve les crédits des projets collaboratifs. Les images réalisées dans le cadre de BuildTheEarth France ne sont pas présentées comme des créations exclusivement personnelles. La rubrique ${link("/buildtheearth/", "BuildTheEarth")} relie ces images à mes outils et à ma documentation communautaire non officielle.</p></section>
      <section><h2>Interfaces, mods et développement</h2><p>Ma ${link(projectPath("iprof-redesign"), "refonte d’iProf")} présente une interface pour les parcours des personnels, avec captures et vidéo. Mes créations publiées sur ${link(SITE.modrinth, "Modrinth")} incluent Colorflow, Nostalgia Ultra Shader et Sculk Vision.</p><p>${link(projectPath("homegui"), "HomeGUI")} est une interface client pour les commandes de homes ; ${link(projectPath("tracebte"), "TraceBTE")} est un tutoriel côté serveur ; ${link(projectPath("railway-tools-axiom"), "Railway Tools")} complète Axiom pour tracer des voies. ${link(projectPath("pineappleui"), "PineappleUI")} explore le passage d’une description d’interface de type HTML/CSS à du code Java Swing.</p><p>Les ${link("/projects/", "fiches de projets, rédigées en anglais")} distinguent les fonctionnalités documentées des limites et des éléments de roadmap. Les forks restent crédités à leurs auteurs d’origine.</p></section>
      <section><h2>Profils et contact</h2><ul><li>${link(SITE.github, "MaxLananas sur GitHub", 'rel="me"')} : code et dépôts publics.</li><li>${link(SITE.modrinth, "maxlananass sur Modrinth", 'rel="me"')} : mes mods, plugins et shaders publiés.</li><li>${link(SITE.instagram, "maxlananas.builds sur Instagram", 'rel="me"')} : publications de créations.</li><li>${link(SITE.discord, "Contacter MaxLananas sur Discord")} : communauté et demandes de projets.</li></ul><p>Pour discuter d’une commande, précise le lieu ou le thème, l’échelle, l’usage attendu et le format de livraison. ${link("/#process", "La méthode de travail")} et ${link("/#contact", "les informations de contact")} sont disponibles sur l’accueil.</p></section>
      <section><h2>Attribution et indépendance</h2><p>Ce site est mon portfolio personnel, pas un site officiel de Minecraft, Mojang, Microsoft, BuildTheEarth ou Axiom. La participation à un projet collectif ne signifie pas que je représente toute l’équipe. Les droits sur les créations présentées restent ceux de leurs auteurs respectifs.</p></section>`;
    return `${languages}<p class="eyebrow">Minecraft building · Software development</p><p>I’m MaxLananas, a Minecraft builder and developer. This portfolio connects my build screenshots, BuildTheEarth-related contributions and the tools I develop for building, navigation and interface creation.</p><p><strong>MaxLananas</strong> is the identity used by this portfolio and my GitHub profile. The accounts below link the projects, published work and contact route together.</p>
      <section><h2>Building and BuildTheEarth</h2><p>The ${link("/builds/", "Minecraft screenshot gallery")} preserves each collaboration’s attribution. Work made within BuildTheEarth France is not presented as exclusively my creation. The ${link("/buildtheearth/", "BuildTheEarth section")} connects these images with my tools and unofficial community documentation.</p></section>
      <section><h2>Interfaces, mods and developer tools</h2><p>My ${link(projectPath("iprof-redesign"), "iProf redesign")} brings interface work into the portfolio through screenshots and a video. My ${link(SITE.modrinth, "Modrinth releases")} include Colorflow, Nostalgia Ultra Shader and Sculk Vision.</p><p>${link(projectPath("homegui"), "HomeGUI")} is a client interface for home commands; ${link(projectPath("tracebte"), "TraceBTE")} is a server-side tutorial; ${link(projectPath("railway-tools-axiom"), "Railway Tools")} extends Axiom for path building. ${link(projectPath("pineappleui"), "PineappleUI")} explores converting HTML/CSS-like interface descriptions into Java Swing code.</p><p>The ${link("/projects/", "project pages")} distinguish documented features from limitations and roadmap items. Forks retain the original authors’ credits.</p></section>
      <section><h2>Profiles and contact</h2><ul><li>${link(SITE.github, "MaxLananas on GitHub", 'rel="me"')}: code and public repositories.</li><li>${link(SITE.modrinth, "maxlananass on Modrinth", 'rel="me"')}: my published mods, plugins and shaders.</li><li>${link(SITE.instagram, "maxlananas.builds on Instagram", 'rel="me"')}: published creations.</li><li>${link(SITE.discord, "Contact MaxLananas on Discord")}: community and project inquiries.</li></ul><p>For a commission, describe the location or theme, scale, intended use and delivery format. Read the ${link("/#process", "building process")} and ${link("/#contact", "contact information")} on the homepage.</p></section>
      <section><h2>Attribution and independence</h2><p>This is my personal portfolio, not an official Minecraft, Mojang, Microsoft, BuildTheEarth or Axiom website. Contributing to a collective project does not mean representing its whole team. The creations shown remain the property of their respective owners.</p></section>`;
  }
  if (page.path === "/projects/") return `<p>A selection of my interface work, published Minecraft projects and software experiments. Releases point to Modrinth; GitHub is used for the public source and lab work.</p>${iprofSpotlight(PROJECTS.find((p) => p.slug === "iprof-redesign"), h, { eager: true })}<section><h2>Published on Modrinth</h2>${cards(PROJECTS.filter((p) => p.collection === "release"))}<p>${link(SITE.modrinth, "Visit my complete Modrinth profile →")}</p></section><section><h2>Software lab</h2><p>Systems, tooling and interface experiments. The project pages distinguish prototypes from published products.</p>${cards(PROJECTS.filter((p) => p.collection === "lab"))}</section><section><h2>Builds and supporting references</h2><p>The earlier BTE tools, documentation and build collections remain available here, with their attribution preserved.</p>${cards(PROJECTS.filter((p) => ["reference", "build"].includes(p.collection)))}</section>`;
  if (page.path === "/buildtheearth/") return `<p>BuildTheEarth is a collaborative effort to recreate real places in Minecraft. My portfolio includes work credited to BuildTheEarth France alongside tools and documentation for related building workflows.</p><p>This page presents <strong>my contributions and projects</strong>, not an official BuildTheEarth service or a claim to represent the project. For the wider initiative and teams, visit ${link(SITE.bte, "the BuildTheEarth website")}.</p><section><h2>From geographic references to Minecraft builds</h2><p>Working from a real location involves more than its appearance. Builders need to identify the place, understand the projected world, lay out a footprint and make recurring decisions about details and infrastructure. My tools address different parts of that workflow rather than one automatic solution.</p><ul><li>${link(projectPath("tracebte"), "TraceBTE teaches a tracing workflow")} using GPS and WorldEdit.</li><li>${link(projectPath("bte-distortion-calculator"), "The BTE Distorsion Calculator explores local scale")} and its model assumptions.</li><li>${link(projectPath("railway-tools-axiom"), "Railway Tools for Axiom lays out paths")} using control points.</li><li>${link(projectPath("bte-france-guidelines"), "The unofficial French guidelines organize building references")} without claiming to replace team decisions.</li></ul></section><section><h2>Projects and credited work</h2>${cards(PROJECTS.filter((p) => p.bte))}</section><section><h2>Shared work needs clear credits</h2><p>A screenshot is not proof of sole authorship of the entire world around it. The ${link("/builds/", "photo catalogue")} keeps credits beside the images, and the ${link(projectPath("builders-utilities-bt-corsica"), "BuildersUtilities adaptation")} names its upstream authors. Refer to each project’s source for its current scope and requirements.</p><p>${link("/about/", "About MaxLananas")} · ${link("/guides/minecraft-mods-plugins-addons/", "Choose between a mod, plugin and addon")}</p></section>`;
  if (page.path === "/development/") return `<p>Interfaces, Minecraft releases and software experiments by ${link("/about/", "MaxLananas")}. Explore the iProf redesign, then the published projects and the lab.</p><nav class="dev-section-nav" aria-label="Development categories"><a href="#interface-work">Interface design</a><a href="#minecraft-releases">Modrinth releases</a><a href="#software-lab">Software lab</a></nav><section id="interface-work" class="dev-featured-section"><h2 class="section-label">Interface work</h2>${iprofSpotlight(PROJECTS.find((p) => p.slug === "iprof-redesign"), h, { eager: true })}</section><section id="minecraft-releases"><p class="eyebrow">Published projects</p><h2>Minecraft, through my tools</h2><p>Color palettes, music interfaces, chunk visualization, shader design and server tools. Modrinth is the main place to find the right release for your version.</p>${cards(PROJECTS.filter((p) => p.collection === "release"))}<p class="section-links">${link(SITE.modrinth, "All my releases on Modrinth ↗")} · ${link("/guides/minecraft-mods-plugins-addons/", "Mods, plugins and addons: which environment?")}</p></section><section id="software-lab"><p class="eyebrow">Beyond Minecraft</p><h2>The software lab</h2><p>SENTINEL explores defensive monitoring in Go, MaxOS explores a small x86 boot and kernel environment with AI-assisted development, and PineappleUI connects interface descriptions to generated Swing code.</p>${cards(PROJECTS.filter((p) => p.collection === "lab"))}<p class="section-links">${link(SITE.github + "?tab=repositories", "Explore the rest of my GitHub repositories ↗")}</p></section><section><h2>Building-related references</h2><p>My BTE-specific tutorials, community documentation and adapted tools have their own context in the ${link("/buildtheearth/", "BuildTheEarth section")}. They remain accessible without taking over the main development selection.</p></section>`;
  if (page.type === "Article") return `<p class="byline">By ${link("/about/", "MaxLananas")} · <time datetime="${SITE.reviewed}">7 September 2026</time></p><p>A Minecraft tool can have a familiar-looking interface while running in a completely different place from another tool. Before downloading a JAR, work out whether it belongs on your client, on the server, or inside the environment of another mod. This guide uses projects from my portfolio to make those boundaries concrete.</p>
    <section><h2>A quick comparison</h2><div class="table-scroll" role="region" aria-label="Tool environment comparison" tabindex="0"><table><caption>Documented environments of the featured tools</caption><thead><tr><th scope="col">Project</th><th scope="col">Runs in</th><th scope="col">Important boundary</th></tr></thead><tbody><tr><th scope="row">${link(projectPath("homegui"), "HomeGUI")}</th><td>Fabric client</td><td>The server still owns the home commands and permissions.</td></tr><tr><th scope="row">${link(projectPath("tracebte"), "TraceBTE")}</th><td>Paper server</td><td>The tutorial needs the documented server tools.</td></tr><tr><th scope="row">${link(projectPath("railway-tools-axiom"), "Railway Tools")}</th><td>Fabric client with Axiom</td><td>Axiom is a separate required dependency.</td></tr><tr><th scope="row">${link(projectPath("bte-distortion-calculator"), "BTE calculator")}</th><td>Browser</td><td>Projection inputs and model state affect interpretation.</td></tr></tbody></table></div></section>
    <section><h2>A client mod can organize information without owning the server feature</h2><p>HomeGUI is a useful example. It reads a server’s response to <code>/homes</code> and makes the destinations searchable in a client interface. Its installation belongs in a matching Fabric setup, but the underlying teleportation behavior belongs to the server. A GUI cannot make an unavailable home command appear or bypass its permission rules.</p><p>When diagnosing a problem, first check whether the command works without the interface. Then inspect the server’s chat format and the versions of Minecraft, Fabric and the mod. This separates a parsing problem from a server permission or command problem.</p></section>
    <section><h2>A server plugin changes the shared server environment</h2><p>TraceBTE provides a guided tracing sequence on a Paper server. Its documentation lists Java, Paper and FAWE requirements, and its tutorial refers to the BTE geographic teleport workflow. Copying it into a client’s <code>mods</code> folder does not provide that environment.</p><p>A server administrator should check dependencies before enabling a tutorial for players. The same distinction applies to the adapted BuildersUtilities plugin: commands, capabilities and access rules are governed by the server and the configured permissions.</p></section>
    <section><h2>An addon depends on the host tool it extends</h2><p>Railway Tools extends Axiom’s tool palette. The addon can generate a path from control points, but it is not a replacement for Axiom. Its loader requirements and Axiom permissions both matter. Check the target versions before assuming that any release of one project works with any release of the other.</p><p>The term “addon” describes a relationship to a host tool here. It should not be confused with a promise that this Java/Fabric project is a Minecraft Bedrock addon.</p></section>
    <section><h2>Some building tools do not run inside Minecraft at all</h2><p>The BTE Distorsion Calculator is a browser tool. Its theoretical and empirical modes help explore scale; they do not place blocks on a server. Check the selected mode and the <code>conformal.lzma</code> grid status before comparing a result with an in-game distance.</p><p>PineappleUI is farther outside the game: its documented target is generated Java Swing code. A <code>.pineui</code> input belongs to that transpiler workflow, not to Minecraft’s mods or plugins folders.</p></section>
    <section><h2>Before installing or reporting a problem</h2><ol><li>Identify where the project runs: client, server, host addon or browser.</li><li>Check its current Minecraft, Java, loader and dependency requirements.</li><li>Distinguish the tool’s interface from permissions and services controlled elsewhere.</li><li>Test a small, reproducible case and include version information in an issue.</li><li>Read the project’s source and license, including upstream credits for a fork.</li></ol><p>These are distinctions supported by the linked project documentation, not compatibility guarantees for future releases. Start from the ${link("/development/", "development catalogue")} and follow the current repository links for installation details.</p></section>`;
  if (page.galleryPage) {
    const first = (page.galleryPage - 1) * PAGE_SIZE;
    const items = FILES.slice(first, first + PAGE_SIZE);
    const total = Math.ceil(FILES.length / PAGE_SIZE);
    const pagination = `<nav class="pagination" aria-label="Gallery pages">${page.galleryPage > 1 ? link(galleryPath(page.galleryPage - 1), "← Previous", 'rel="prev"') : ""}${Array.from({ length: total }, (_, i) => i + 1).map((n) => link(galleryPath(n), `Page ${n}`, n === page.galleryPage ? 'aria-current="page"' : "")).join("")}${page.galleryPage < total ? link(galleryPath(page.galleryPage + 1), "Next →", 'rel="next"') : ""}</nav>`;
    return `<p>Screenshots ${first + 1}–${first + items.length} of ${FILES.length}. This catalogue keeps every original image and its existing collaboration credit. Multiple views can belong to the same build; the image count is not a count of independent projects.</p><p>Every page and image link works without JavaScript. For filters and the lightbox, use ${link("/#work", "the interactive gallery")}; for context, read ${link(projectPath("le-mans"), "the Le Mans collection")} or ${link("/buildtheearth/", "the BuildTheEarth overview")}.</p>${pagination}${photos(items)}${pagination}<section><h2>Image credits and original files</h2><p>Named images use descriptions supported by the portfolio catalogue. Unnamed captures are left as numbered screenshots rather than assigning an unverified location or project. The original-file links may download a large image; screenshots are not world or schematic downloads.</p><p>The creations shown remain the property of their respective owners. ${link("/about/", "Read about MaxLananas and attribution")}.</p></section>`;
  }
  throw new Error(`No content renderer for ${page.path}`);
}
